export enum getUserDataType {
  GET_USERS_INFO = 'GET_USERS_INFO',
  GET_USERS_INFO_FAIL = 'GET_USERS_INFO_FAIL',
  GET_USERS_INFO_SUCCESS = 'GET_USERS_INFO_SUCCESS',
  DATA_DELETE = 'DATA_DELETE',

  RESET_EDITING = 'RESET_EDITING',
  EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL',
  EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS',
}

