export enum getDepartmentsType {
  GET_DEPARTMENTS = 'GET_DEPARTMENTS',
  GET_DEPARTMENTS_FAIL = 'GET_DEPARTMENTS_FAIL',
  GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS',
  SHOW_WARNING = 'SHOW_WARNING',
  CANCEL_DELETE = 'CANCEL_DELETE',
  ADD_DEP_FAIL = 'ADD_DEP_FAIL',
  RESET_DEPARTMENTS_ERRORS = 'RESET_DEPARTMENTS_ERRORS',
  SHOW_DEPARTMENT = 'SHOW_DEPARTMENT',
  RESET_EDITING = 'RESET_EDITING',
  EDIT_DEP_FAIL = 'EDIT_DEP_FAIL',
}