export enum getMeetingRoomsDataType {
  GET_MEETING_ROOMS_INFO = 'GET_MEETING_ROOMS_INFO',
  GET_MEETING_ROOMS_INFO_FAIL = 'GET_MEETING_ROOMS_INFO_FAIL',
  GET_MEETING_ROOMS_INFO_SUCCESS = 'GET_MEETING_ROOMS_INFO_SUCCESS',
  GET_CHECKED_MRS_ID='GET_CHECKED_MRS_ID',
}

