export enum getMeetingRoomsDataType {
  GET_MEETING_ROOMS_INFO = 'GET_MEETING_ROOMS_INFO',
  GET_MEETING_ROOMS_INFO_FAIL = 'GET_MEETING_ROOMS_INFO_FAIL',
  GET_MEETING_ROOMS_INFO_SUCCESS = 'GET_MEETING_ROOMS_INFO_SUCCESS',
}

