export enum getReservationsType {
  GET_RESERVATIONS = 'GET_RESERVATIONS',
  GET_RESERVATIONS_FAIL = 'GET_RESERVATIONS_FAIL',
  GET_RESERVATIONS_SUCCESS = 'GET_RESERVATIONS_SUCCESS',
  // SHOW_RESERVATIONS = 'SHOW_RESERVATIONS',
  // RESET_EDITING = 'RESET_EDITING',
  SHOW_WARNING = 'SHOW_WARNING',
  CANCEL_DELETE = 'CANCEL_DELETE',
}

